// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package test

import mock "github.com/stretchr/testify/mock"

// TMock is an autogenerated mock type for the T type
type TMock struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *TMock) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Error provides a mock function with given fields: args
func (_m *TMock) Error(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Errorf provides a mock function with given fields: format, args
func (_m *TMock) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Fatal provides a mock function with given fields: args
func (_m *TMock) Fatal(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Fatalf provides a mock function with given fields: format, args
func (_m *TMock) Fatalf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Helper provides a mock function with given fields:
func (_m *TMock) Helper() {
	_m.Called()
}

// Log provides a mock function with given fields: args
func (_m *TMock) Log(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Logf provides a mock function with given fields: format, args
func (_m *TMock) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}
